# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MusicFM' do
pod 'FMDB', '~> 2.5'
pod 'YTKKeyValueStore', '~> 0.1.2'
pod 'AFNetworking', '~> 3.0.0-beta.3'
pod 'YYWebImage', '~> 0.9.11'
pod 'MJRefresh', '~> 3.0.7'
pod 'Masonry', '~> 0.6.3'
end

target 'MusicFMTests' do

end

target 'MusicFMUITests' do

end

